canton {
  participants {
    participant1 {
      storage.type = memory
      admin-api.port = 5012
      ledger-api {
        port = 5011
        address = "127.0.0.1"
      }
      http-ledger-api {
        port = 7575
        address = "127.0.0.1"
      }
    }
  }
}
